version: '3.8'
services:
  mysql-container:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_admin
      MYSQL_DATABASE: admin_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

